- name: ensure services are stopped
  community.general.snap:
    name: amazon-ssm-agent
    state: absent

- name: ensure services are stopped and disabled for first boot
  systemd:
    enabled: no
    name: '{{ item }}'
    state: stopped
  with_items:
    - snapd
    - postgresql
    - pgbouncer
    - fail2ban
    - man-db

- name: Setup - install common dependencies
  apt:
    state: absent
    pkg:
      - snapd

- name: ensure services are stopped and disabled for first boot
  systemd:
    enabled: no
    name: '{{ item }}'
    state: stopped
    masked: yes
  with_items:
    - lvm2-monitor
    - man-db
