- name: override defaults
  copy:
    src: files/fail2ban_config/jail-customizations
    dest: /etc/fail2ban/jail.d/customizations.local

- name: Configure ssh jail
  copy:
    src: files/fail2ban_config/jail-ssh.conf
    dest: /etc/fail2ban/jail.d/sshd.local

- name: import jail.d/postgresql.conf
  template:
    src: files/fail2ban_config/jail-postgresql.conf.j2
    dest: /etc/fail2ban/jail.d/postgresql.conf

- name: import filter.d/postgresql.conf
  template:
    src: files/fail2ban_config/filter-postgresql.conf.j2
    dest: /etc/fail2ban/filter.d/postgresql.conf

- name: fail2ban - restart
  systemd:
    name: fail2ban
    state: restarted
