- name: Install postgis for postgreSQL versions < 10
  apt:
    pkg:
    - libgeos-c1v5
    - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}"
    - "postgresql-{{ postgresql_version }}-postgis-scripts"
    update_cache: yes
    cache_valid_time: 3600
  when: postgresql_version < 10

- name: Install postgis for postgreSQL versions >= 10
  apt:
    pkg:
    - libgeos-c1v5
    - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}"
    - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}-scripts"
    update_cache: yes
    cache_valid_time: 3600
  when: postgresql_version >= 10

- name: pgTAP - download latest releas
  get_url:
    url: "https://github.com/theory/pgtap/archive/{{ pgtap_release }}.tar.gz"
    dest: /tmp
    checksum: "{{ pgtap_release_checksum }}"

- name: pgTAP - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/pgtap-1.1.0.tar.gz
    dest: /tmp
  become: yes

- name: pgTAP - install
  make:
    chdir: /tmp/pgtap-1.1.0
    target: install
  become: yes