# WAL-G
- name: Install daemontools
  become: yes
  apt:
    pkg:
      - daemontools

- name: wal-g system dependencies
  apt:
    pkg:
      - liblzo2-dev
      - cmake
      - build-essential

# find platform architecture
- name: finding platform architecture
  shell: if [ $(uname -m) = "aarch64" ]; then echo "arm64";  else echo "amd64"; fi
  register: platform_output
- set_fact:
    platform: "{{ platform_output.stdout }}"

# install go dependency for WAL-G
- name: wal-g go dependency
  get_url:
    url: "https://golang.org/dl/go{{ golang_version }}.linux-{{ platform }}.tar.gz"
    dest: /tmp
- name: unpack go archive
  unarchive:
    remote_src: yes
    src: "/tmp/go{{ golang_version }}.linux-{{ platform }}.tar.gz"
    dest: /usr/local

# Download WAL-G
- name: download wal-g
  shell:
    cmd: go get github.com/wal-g/wal-g;
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
  ignore_errors: yes
  # ignore error https://github.com/wal-g/wal-g/issues/343#issuecomment-514544288

# Install WAL-G
- name: install wal-g
  become: yes
  shell:
    cmd: make install && make deps && make pg_install
    chdir: "{{ ansible_env.HOME }}/go/src/github.com/wal-g/wal-g"
  environment:
    GOBIN: "/usr/local/bin"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"

# PgBouncer
- name: PgBouncer - download & install dependencies
  apt:
    pkg:
      - libssl-dev
      - pkg-config
      - libevent-dev
    update_cache: yes
    cache_valid_time: 3600

- name: PgBouncer - download latest release
  get_url:
    url: "https://www.pgbouncer.org/downloads/files/{{ pgbouncer_release }}/pgbouncer-{{ pgbouncer_release }}.tar.gz"
    dest: /tmp/pgbouncer-{{ pgbouncer_release }}.tar.gz
    checksum: "{{ pgbouncer_release_checksum }}"

- name: PgBouncer - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/pgbouncer-{{ pgbouncer_release }}.tar.gz
    dest: /tmp
  become: yes

- name: PgBouncer - configure
  shell:
    cmd: "./configure --prefix=/usr/local --with-systemd"
    chdir: /tmp/pgbouncer-{{ pgbouncer_release }}
  become: yes

- name: PgBouncer - build
  make:
    chdir: /tmp/pgbouncer-{{ pgbouncer_release }}
  become: yes

- name: PgBouncer - install
  make:
    chdir: /tmp/pgbouncer-{{ pgbouncer_release }}
    target: install
  become: yes

# Create /etc/postgresql directory and make sure postgres group owns it
- name: Create a directory if it does not exist
  file:
    path: /etc/pgbouncer
    state: directory
    group: postgres
