- name: AWS CLI dep
  apt:
    pkg:
      - unzip
    install_recommends: no

- name: AWS CLI (arm)
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-aarch64-{{ aws_cli_release }}.zip"
    dest: "/tmp/awscliv2.zip"
  when: platform == "arm64"

- name: AWS CLI (x86)
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-{{ platform_aws }}-{{ aws_cli_release }}.zip"
    dest: "/tmp/awscliv2.zip"
  when: platform == "amd64"

- name: AWS CLI - expand
  unarchive:
    remote_src: yes
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"

- name: AWS CLI - install
  shell: "/tmp/aws/install"
  become: true

- name: Install Postgres exporter
  import_tasks: postgres-exporter.yml

- name: Install node exporter
  import_tasks: node-exporter.yml

# supautils
- name: supautils - download latest release
  get_url:
    url: "https://github.com/supabase/supautils/archive/refs/tags/v{{ supautils_release }}.tar.gz"
    dest: /tmp/supautils-{{ supautils_release }}.tar.gz
    checksum: "{{ supautils_release_checksum }}"

- name: supautils - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/supautils-{{ supautils_release }}.tar.gz
    dest: /tmp
  become: yes

- name: supautils - build
  make:
    chdir: /tmp/supautils-{{ supautils_release }}
  become: yes

- name: supautils - install
  make:
    chdir: /tmp/supautils-{{ supautils_release }}
    target: install
  become: yes

- name: supautils - set supautils.reserved_roles
  become: yes
  lineinfile:
    path: /etc/postgresql/postgresql.conf
    state: present
    line: supautils.reserved_roles = 'supabase_admin, supabase_auth_admin, supabase_storage_admin, dashboard_user, pgbouncer, service_role, authenticator, authenticated, anon'

- name: supautils - set supautils.reserved_memberships
  become: yes
  lineinfile:
    path: /etc/postgresql/postgresql.conf
    state: present
    line: supautils.reserved_memberships = 'pg_read_server_files, pg_write_server_files, pg_execute_server_program'

- name: supautils - add supautils to shared_preload_libraries
  become: yes
  replace:
    path: /etc/postgresql/postgresql.conf
    regexp: shared_preload_libraries = '
    replace: shared_preload_libraries = 'supautils,
