- name: Install postgis for postgreSQL versions < 10
  apt:
    pkg:
    - libgeos-c1v5
    - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}"
    - "postgresql-{{ postgresql_version }}-postgis-scripts"
    update_cache: yes
    cache_valid_time: 3600
  when: postgresql_version < 10

- name: Install postgis for postgreSQL versions >= 10
  apt:
    pkg:
    - libgeos-c1v5
    - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}"
    - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}-scripts"
    update_cache: yes
    cache_valid_time: 3600
  when: postgresql_version >= 10

- name: pgTAP - download latest release
  get_url:
    url: "https://github.com/theory/pgtap/archive/{{ pgtap_release }}.tar.gz"
    dest: /tmp
    checksum: "{{ pgtap_release_checksum }}"

- name: pgTAP - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/pgtap-1.1.0.tar.gz
    dest: /tmp
  become: yes

- name: pgTAP - install
  make:
    chdir: /tmp/pgtap-1.1.0
    target: install
  become: yes

- name: Install plpython
  apt:
    pkg: postgresql-plpython3-12
    update_cache: yes
    cache_valid_time: 3600

- name: pgAudit - download & install dependencies
  apt:
    pkg:
      - postgresql-server-dev-12
      - libssl-dev
      - libkrb5-dev
    update_cache: yes
    install_recommends: no

- name: pgAudit - download latest release
  git:
    repo: https://github.com/pgaudit/pgaudit.git
    dest: /tmp/pgaudit
  become: yes

- name: pgAudit - build
  make: 
    chdir: /tmp/pgaudit
    target: check
    params:
      USE_PGXS: 1
  become: yes

- name: pgAudit - install
  make:
    chdir: /tmp/pgaudit
    target: install
    params:
      USE_PGXS: 1
  become: yes

- name: plv8 - download & install dependencies
  apt:
    pkg:
      - build-essential
      - ca-certificates
      - curl
      - git-core
      - gpp
      - cpp
      - pkg-config
      - apt-transport-https
      - cmake
      - libc++-dev
      - libc++abi-dev
      - postgresql-server-dev-12
      - libc++1
      - libtinfo5
      - libc++abi1
    update_cache: yes
    install_recommends: no

- name: plv8 - download latest release
  git:
    repo: https://github.com/plv8/plv8.git
    dest: /tmp/plv8
    version: r3.0alpha
  become: yes

- name: plv8 - build
  make: 
    chdir: /tmp/plv8
  become: yes

- name: plv8 - install
  make:
    chdir: /tmp/plv8
    target: install
  become: yes

- name: plv8 - remove build dependencies
  apt:
    pkg:
      - ca-certificates
      - curl
      - git-core
      - python
      - gpp
      - cpp
      - pkg-config
      - apt-transport-https
      - cmake
      - libc++-dev
      - libc++abi-dev
      - postgresql-server-dev-12
