## [WIP]
## TODO
## Checks to ensure:
### directories exist
### directories are owned by postgres
### verify LSE is enabled
### database is running

- name: Start Postgres Server
  systemd:
    name: postgresql
    state: started