- name: AWS CLI dep
  apt:
    pkg:
      - unzip
    install_recommends: no

- name: AWS CLI
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-aarch64-{{ aws_cli_release }}.zip"
    dest: "/tmp/awscliv2.zip"

- name: AWS CLI - expand
  unarchive:
    remote_src: yes
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"

- name: AWS CLI - install
  shell: "/tmp/aws/install"
  become: true

- name: Install Postgres exporter
  import_tasks: postgres-exporter.yml

- name: Install node exporter
  import_tasks: node-exporter.yml
