# DigitalOcean's ubuntu droplet isn't up to date with installed packages, and on
# a fresh install I see 71 security upgrades available.
- name: System - apt update and apt upgrade
  apt: update_cache=yes upgrade=yes
  # SEE http://archive.vn/DKJjs#parameter-upgrade

- name: Install essentials
  apt:
    pkg:
      - ufw
    update_cache: yes
    cache_valid_time: 3600

- name: Install psycopg2 to enable ansible postgreSQL features
  pip: name=psycopg2-binary

- name: System - Create services.slice
  template:
    src: files/services.slice.j2
    dest: /etc/systemd/system/services.slice

- name: System - systemd reload
  systemd: daemon_reload=yes

