- name: Install Python3
  raw: apt update && apt upgrade -y && apt install python3 -y

- name: Setup - install common dependencies
  apt:
    pkg:
      - rsync
      - ca-certificates
      - build-essential
      - postgresql-server-dev-13
      - curl
      - git-core
      - gpp
      - cpp
      - pkg-config
      - apt-transport-https
      - cmake
      - ninja-build
      - python
    update_cache: yes
    install_recommends: no

# Find platform architecture and set as a variable
- name: Setup - finding platform architecture
  shell: if [ $(uname -m) = "aarch64" ]; then echo "arm64";  else echo "amd64"; fi
  register: platform_output
- set_fact:
    platform: "{{ platform_output.stdout }}"

- name: Setup - import postgresql.conf
  synchronize:
    src: files/postgresql_config/postgresql.conf.j2
    dest: etc/postgresql/postgresql.conf

- name: Setup - import pg_hba.conf
  template:
    src: files/postgresql_config/pg_hba.conf.j2
    dest: etc/postgresql/pg_hba.conf

- name: Setup - import pg_ident.conf
  template:
    src: files/postgresql_config/pg_ident.conf.j2
    dest: etc/postgresql/pg_ident.conf

- name: Setup - add init script to /docker-entrypoint-initdb.d
  synchronize:
    src: files/docker_mnt/init.sh
    dest: /docker-entrypoint-initdb.d/init.sh