- hosts: all
  become: yes

  pre_tasks:
    - import_tasks: tasks/setup-system.yml
  
  vars_files:
    - ./vars.yml
  
  roles:
    - role: anxs.postgresql

  tasks:
    - import_tasks: tasks/setup-extensions.yml

    - name: Dump SQL script
      copy:
        dest: /tmp/00-schema.sql
        src: ../docker/mnt/00-schema.sql

    - name: Set up readonly user for the public schema
      become: yes
      become_user: postgres
      postgresql_query:
        db: postgres
        path_to_script: /tmp/00-schema.sql

    - name: Delete SQL script
      file:
        path: /tmp/00-schema.sql
        state: absent
    
    - name: Adjust APT update intervals
      copy: 
        src: files/apt_periodic
        dest: /etc/apt/apt.conf.d/10periodic

    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Allow connections to postgreSQL (5432)
      ufw:
        rule: allow
        port: '5432'

    - name: UFW - Deny all other incoming traffix by default
      ufw: 
        state: enabled
        policy: deny
        direction: incoming