- hosts: all
  become: yes

  pre_tasks:
    - import_tasks: tasks/setup-system.yml

  vars_files:
    - ./vars.yml

  vars:
    sql_files:
      - { source: "pgbouncer_auth_schema.sql", dest: "00-schema.sql" }
      - { source: "stat_extension.sql", dest: "01-extension.sql" }

  environment:
    PATH: /usr/lib/postgresql/bin:{{ ansible_env.PATH }}

  tasks:
    - name: Install Postgres from source
      import_tasks: tasks/setup-postgres.yml
    
    - name: Install WAL-G
      import_tasks: tasks/setup-wal-g.yml

    - name: Install PgBouncer
      import_tasks: tasks/setup-pgbouncer.yml
      when: install_pgbouncer == true

    - name: Install PostgREST
      import_tasks: tasks/setup-postgrest.yml
      when: install_postgrest == true

    - name: Install Postgres extensions
      import_tasks: tasks/setup-extensions.yml

    - name: Install Supabase specific content
      import_tasks: tasks/setup-supabase-internal.yml
      when: supabase_internal == true

    - name: Start Postgres and perform checks
      import_tasks: tasks/setup-postgres-init.yml

    - name: Adjust APT update intervals
      copy:
        src: files/apt_periodic
        dest: /etc/apt/apt.conf.d/10periodic

    - name: Transfer init SQL files
      copy:
        src: files/{{ item.source }}
        dest: /tmp/{{ item.dest }}
      loop: "{{ sql_files }}"

    - name: Execute init SQL files
      become: yes
      become_user: postgres
      shell:
        cmd: /usr/lib/postgresql/bin/psql -f /tmp/{{ item.dest }}
      loop: "{{ sql_files }}"

    - name: Delete SQL scripts
      file:
        path: /tmp/{{ item.dest }}
        state: absent
      loop: "{{ sql_files }}"

    - name: Adjust pgbouncer.ini
      copy:
        src: files/pgbouncer.ini
        dest: /etc/pgbouncer/pgbouncer.ini

    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Allow connections to postgreSQL (5432)
      ufw:
        rule: allow
        port: "5432"

    - name: UFW - Allow connections to postgreSQL (6543)
      ufw:
        rule: allow
        port: "6543"

    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Setup logrotate for postgres logs
      copy:
        src: files/logrotate-postgres
        dest: /etc/logrotate.d/postgres
