postgresql_version: 12
postgresql_wal_level: "logical"
postgresql_max_wal_senders: 10
postgresql_max_replication_slots: 5
postgresql_listen_addresses:
  - "*"

postgresql_ext_install_contrib: yes
postgresql_ext_install_dev_headers: yes

# Warning: Make sure the postgresql & postgis versions are compatible with one another
postgresql_ext_postgis_version: 3

postgresql_shared_preload_libraries: [pg_stat_statements, pgaudit]

postgresql_pg_hba_custom:
  - {type: "host", database: "all", user: "all", address: "0.0.0.0/0", method: "md5" }

pgtap_release: "1.1.0"
pgtap_release_checksum: sha1:cca57708e723de18735a723b774577dc52f6f31e

pgaudit_release: "1.4.0"
pgaudit_release_checksum: sha1:ea085fbf227b5c461331ab33b99579f37db299a6

postgresql_log_destination: "csvlog"
postgresql_logging_collector: on
postgresql_log_filename: "postgresql.log"
postgresql_log_rotation_age: 0
postgresql_log_rotation_size: 0