name: Release on Dockerhub

on:
  push:
    branches:
      # - develop
      - drag/test_docker_14_june
    paths:
      - ".github/workflows/dockerhub-release.yml"
      - "docker.vars*"
      - "Dockerfile"

jobs:
  docker_release:
    runs-on: [self-hosted, linux]
    timeout-minutes: 150
    steps:
      - uses: actions/checkout@v2

      - id: settings
        run: |
          apt update --yes && apt install --yes jq
          DOCKER_VERSION=$(cat docker.vars.json | jq -r '.["docker-version"]')
          echo "::set-output name=docker_version::$DOCKER_VERSION"

          POSTGRES_VERSION=$(cat docker.vars.json | jq -r '.["postgres-version"]')
          echo "::set-output name=postgres_version::$POSTGRES_VERSION"

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: supabase/postgres:${{ steps.settings.outputs.docker_version }}
          platforms: linux/amd64
          build-args: |
            "VERSION=${{steps.settings.outputs.postgres_version}}"
