name: Release on Dockerhub

on:
  workflow_dispatch:
  push:
    branches:
      - patch-1
    paths:
      - '.github/workflows/dockerhub-release.yml'
      - 'docker.vars*'

jobs:
  docker_release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - id: settings
        run:  |
          apt update --yes && apt install --yes jq
          DOCKER_VERSION=$(cat docker.vars.json | jq -r '.["docker-version"]')
          echo "::set-output name=docker_version::$DOCKER_VERSION"

          POSTGRES_VERSION=$(cat docker.vars.json | jq -r '.["postgres-version"]')
          echo "::set-output name=postgres_version::$POSTGRES_VERSION"

          PLATFORM=$(cat docker.vars.json | jq -r '.["platform"]')
          echo "::set-output name=platform::$PLATFORM"

      - uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/aarondewes/postgres:latest,ghcr.io/aarondewes/postgres:${{ steps.settings.outputs.docker_version }}
          platforms: linux/arm64
          build-args: |
            "VERSION=${{steps.settings.outputs.postgres_version}}"
