name: Run CI checks

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [docker-arm64]
    timeout-minutes: 150

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: supabase/postgres:latest,supabase/postgres:v${{ version }}
          platforms: linux/arm64
